# Generated by Django 6.0.5 on 2026-05-28 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0003_add_fks_and_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referral',
            options={'ordering': ['-created_at']},
        ),
    ]
