# Generated by Django 6.0.5 on 2026-05-28 12:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TraineeSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anonymous_token', models.CharField(max_length=255)),
                ('consent', models.BooleanField(default=False)),
                ('gender', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScreeningResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcl5_score', models.IntegerField()),
                ('dts_score', models.IntegerField()),
                ('severity', models.CharField(choices=[('minimal', 'Minimal'), ('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('critical', 'Critical')], max_length=20)),
                ('prediction_confidence', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trainee_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screening.traineesession')),
            ],
        ),
    ]
