# Generated by Django 6.0.5 on 2026-05-28 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0002_add_pcl5_items_and_clusters'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='screeningresult',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='traineesession',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='screeningresult',
            name='trainee_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='screening.traineesession'),
        ),
    ]
