# Generated by Django 6.0.5 on 2026-06-15 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0003_alter_screeningresult_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='traineesession',
            name='student',
            field=models.ForeignKey(blank=True, help_text='Linked student account (optional, for tracking)', limit_choices_to={'role': 'student'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screening_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
