# Generated by Django 6.0.5 on 2026-05-28 16:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp_engine', '0002_add_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nlpresult',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='nlpresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
