# Generated by Django 6.0.5 on 2026-05-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp_engine', '0003_alter_nlpresult_options_alter_nlpresult_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nlpresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
